steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions',
         'deploy',
         'UpdateDisneyQueues',
         '--trigger-http',
         '--runtime', 'Python 3.11',
         '--entry-point', 'main']